// <auto-generated />
using System;
using Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260428080556_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Checklist")
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Aggregates.Assessments.Assessment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AssessmentDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<Guid>("ChecklistId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ChecklistVersion")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("CreatedAt")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<Guid?>("CreatedById")
                        .HasMaxLength(450)
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("CreatedById");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("DeletedAt");

                    b.Property<Guid?>("DeletedById")
                        .HasMaxLength(450)
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("DeletedById");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<float>("TotalScore")
                        .HasColumnType("real");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("UpdatedAt");

                    b.Property<Guid?>("UpdatedById")
                        .HasMaxLength(450)
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("UpdatedById");

                    b.HasKey("Id");

                    b.HasIndex("AssessmentDate");

                    b.HasIndex("ChecklistId");

                    b.HasIndex("ChecklistVersion");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_Assessments_CreatedAt");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("IX_Assessments_IsDeleted");

                    b.HasIndex("UpdatedAt")
                        .HasDatabaseName("IX_Assessments_UpdatedAt");

                    b.ToTable("Assessments", "Checklist");
                });

            modelBuilder.Entity("Domain.Aggregates.Assessments.AssessmentAnswer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AnswerText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("AssessmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("CreatedAt")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<Guid?>("CreatedById")
                        .HasMaxLength(450)
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("CreatedById");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("DeletedAt");

                    b.Property<Guid?>("DeletedById")
                        .HasMaxLength(450)
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("DeletedById");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SelectedOptionIds")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("UpdatedAt");

                    b.Property<Guid?>("UpdatedById")
                        .HasMaxLength(450)
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("UpdatedById");

                    b.HasKey("Id");

                    b.HasIndex("AssessmentId");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_AssessmentAnswer_CreatedAt");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("IX_AssessmentAnswer_IsDeleted");

                    b.HasIndex("QuestionId");

                    b.HasIndex("UpdatedAt")
                        .HasDatabaseName("IX_AssessmentAnswer_UpdatedAt");

                    b.ToTable("AssessmentAnswer", "Checklist");
                });

            modelBuilder.Entity("Domain.Aggregates.Checklists.Checklist", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("CreatedAt")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<Guid?>("CreatedById")
                        .HasMaxLength(450)
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("CreatedById");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("DeletedAt");

                    b.Property<Guid?>("DeletedById")
                        .HasMaxLength(450)
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("DeletedById");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsValid")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastModified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("UpdatedAt");

                    b.Property<Guid?>("UpdatedById")
                        .HasMaxLength(450)
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("UpdatedById");

                    b.Property<int>("Version")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_Checklists_CreatedAt");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("IX_Checklists_IsDeleted");

                    b.HasIndex("Title");

                    b.HasIndex("UpdatedAt")
                        .HasDatabaseName("IX_Checklists_UpdatedAt");

                    b.ToTable("Checklists", "Checklist");
                });

            modelBuilder.Entity("Domain.Aggregates.Checklists.ChecklistGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ChecklistId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("CreatedAt")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<Guid?>("CreatedById")
                        .HasMaxLength(450)
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("CreatedById");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("DeletedAt");

                    b.Property<Guid?>("DeletedById")
                        .HasMaxLength(450)
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("DeletedById");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsShow")
                        .HasColumnType("bit");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("UpdatedAt");

                    b.Property<Guid?>("UpdatedById")
                        .HasMaxLength(450)
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("UpdatedById");

                    b.HasKey("Id");

                    b.HasIndex("ChecklistId");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_ChecklistGroup_CreatedAt");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("IX_ChecklistGroup_IsDeleted");

                    b.HasIndex("ParentId");

                    b.HasIndex("UpdatedAt")
                        .HasDatabaseName("IX_ChecklistGroup_UpdatedAt");

                    b.ToTable("ChecklistGroup", "Checklist");
                });

            modelBuilder.Entity("Domain.Aggregates.Checklists.ChecklistQuestion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("CreatedAt")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<Guid?>("CreatedById")
                        .HasMaxLength(450)
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("CreatedById");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("DeletedAt");

                    b.Property<Guid?>("DeletedById")
                        .HasMaxLength(450)
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("DeletedById");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRequiredAnswer")
                        .HasColumnType("bit");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<float?>("Score")
                        .HasColumnType("real");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("UpdatedAt");

                    b.Property<Guid?>("UpdatedById")
                        .HasMaxLength(450)
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("UpdatedById");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_ChecklistQuestion_CreatedAt");

                    b.HasIndex("GroupId");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("IX_ChecklistQuestion_IsDeleted");

                    b.HasIndex("UpdatedAt")
                        .HasDatabaseName("IX_ChecklistQuestion_UpdatedAt");

                    b.ToTable("ChecklistQuestion", "Checklist");
                });

            modelBuilder.Entity("Domain.Aggregates.Checklists.ChecklistQuestionOption", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ChecklistQuestionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("CreatedAt")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<Guid?>("CreatedById")
                        .HasMaxLength(450)
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("CreatedById");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("DeletedAt");

                    b.Property<Guid?>("DeletedById")
                        .HasMaxLength(450)
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("DeletedById");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("UpdatedAt");

                    b.Property<Guid?>("UpdatedById")
                        .HasMaxLength(450)
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("UpdatedById");

                    b.HasKey("Id");

                    b.HasIndex("ChecklistQuestionId");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_ChecklistQuestionOption_CreatedAt");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("IX_ChecklistQuestionOption_IsDeleted");

                    b.HasIndex("UpdatedAt")
                        .HasDatabaseName("IX_ChecklistQuestionOption_UpdatedAt");

                    b.ToTable("ChecklistQuestionOption", "Checklist");
                });

            modelBuilder.Entity("Domain.Aggregates.Assessments.Assessment", b =>
                {
                    b.HasOne("Domain.Aggregates.Checklists.Checklist", "Checklist")
                        .WithMany()
                        .HasForeignKey("ChecklistId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Checklist");
                });

            modelBuilder.Entity("Domain.Aggregates.Assessments.AssessmentAnswer", b =>
                {
                    b.HasOne("Domain.Aggregates.Assessments.Assessment", "Assessment")
                        .WithMany("Answers")
                        .HasForeignKey("AssessmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Aggregates.Checklists.ChecklistQuestion", "Question")
                        .WithMany()
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Assessment");

                    b.Navigation("Question");
                });

            modelBuilder.Entity("Domain.Aggregates.Checklists.ChecklistGroup", b =>
                {
                    b.HasOne("Domain.Aggregates.Checklists.Checklist", "Checklist")
                        .WithMany("Groups")
                        .HasForeignKey("ChecklistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Aggregates.Checklists.ChecklistGroup", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId");

                    b.Navigation("Checklist");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Domain.Aggregates.Checklists.ChecklistQuestion", b =>
                {
                    b.HasOne("Domain.Aggregates.Checklists.ChecklistGroup", "Group")
                        .WithMany("Questions")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");
                });

            modelBuilder.Entity("Domain.Aggregates.Checklists.ChecklistQuestionOption", b =>
                {
                    b.HasOne("Domain.Aggregates.Checklists.ChecklistQuestion", "ChecklistQuestion")
                        .WithMany("Options")
                        .HasForeignKey("ChecklistQuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChecklistQuestion");
                });

            modelBuilder.Entity("Domain.Aggregates.Assessments.Assessment", b =>
                {
                    b.Navigation("Answers");
                });

            modelBuilder.Entity("Domain.Aggregates.Checklists.Checklist", b =>
                {
                    b.Navigation("Groups");
                });

            modelBuilder.Entity("Domain.Aggregates.Checklists.ChecklistGroup", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("Questions");
                });

            modelBuilder.Entity("Domain.Aggregates.Checklists.ChecklistQuestion", b =>
                {
                    b.Navigation("Options");
                });
#pragma warning restore 612, 618
        }
    }
}
